### ISSUE TITLE
Possible Bug or I've overlooked something

### ISSUE THREAD

**Issue by ClaudeCundiff** [stchris/untangle#20]
<p>I've noticed that if there is only one "prop" under a "group," then I get the output as illustrated. Any thoughts?</p>
<code>main.py</code>
![main_py](https://cloud.githubusercontent.com/assets/16643648/12241673/16058cfe-b85a-11e5-9f5c-96e9e388bf4f.png)
<code>figs.xml</code>
![figs](https://cloud.githubusercontent.com/assets/16643648/12241674/19ceeeb6-b85a-11e5-8c22-399c89ce82a8.png)
<h3>Results</h3>
![screenshot from 2016-01-11 09 57 08](https://cloud.githubusercontent.com/assets/16643648/12241694/3056a5e8-b85a-11e5-9cd1-24ae2a5ab2ec.png)

**Comment by stchris** [comment]
This is because there is an unexpected inconsistency in the returned object: when you have only one child (`prop` in the second group), you can access it with `.prop`, whereas when you have more than one you actually use `.prop[0]`, `.prop[1]` etc. Unfortunately you would have to treat the case of `r == 0` differently. See also the first two examples in `examples.py`.

**Comment by ClaudeCundiff** [comment]
Ok, thanks for explaining that. I really have to say, I love this module,
it's very helpful. Not sure if you're looking for any help on this project,
but if you need anything, I'll do what I can.

On Tue, Jan 12, 2016 at 2:00 PM, Christian Stefanescu <
notifications@github.com> wrote:

> Closed #20 <https://github.com/stchris/untangle/issues/20>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stchris/untangle/issues/20#event-512854906>.
>



-- 
Sincerely,

Claude E. Cundiff
804.490.8961

I’m always pursuing the opportunity to utilize information technology as a
means of implementing effective and efficient solutions to unique and
interesting business challenges.
